import assert from 'node:assert/strict';
import { getCapturePreferences,setCapturePreferences,saveActivity,clearSavedActivity } from './activity.js';
import { setSessionToken,clearSessionToken } from './storage.js';
import { createDraftRecorder } from './draft-recorder.js';
global.localStorage={store:{},getItem(k){return this.store[k]||null;},setItem(k,v){this.store[k]=String(v);},removeItem(k){delete this.store[k];}};
let requests=[];
let enabled=false;
global.fetch=async(url,options)=>{
  requests.push({url,options});
  let data={saveDrafts:enabled,saveSearches:enabled,disclosureVersion:'2026-09-13-v2'};
  if(url.includes('preferences')&&options.method==='POST') {enabled=JSON.parse(options.body).saveDrafts;data=JSON.parse(options.body);}
  if(url.includes('activity'))data={saved:true,success:true};
  return {ok:true,json:async()=>data};
};
const entry={kind:'draft',clientId:crypto.randomUUID(),text:'Private draft',platform:'chatgpt',mode:'standard',revision:1};
assert.equal((await saveActivity(entry)).saved,false);
assert.equal(requests.length,0,'Signed-out draft must not make a network request');
await setSessionToken('account-a');
assert.equal((await saveActivity(entry)).saved,false);
assert(!requests.some(r=>r.options.body?.includes('Private draft')),'No draft text before consent');
await setCapturePreferences({saveDrafts:true,saveSearches:true});
assert.equal((await saveActivity(entry)).saved,true);
assert(requests.some(r=>r.options.headers.Authorization==='Bearer account-a'&&r.options.body?.includes('Private draft')));
enabled=false;
await setSessionToken('account-b');
assert.equal((await getCapturePreferences()).saveDrafts,false,'Consent cannot cross accounts');
assert.equal((await saveActivity(entry)).saved,false);
await clearSavedActivity();
await clearSessionToken();
requests=[];
await saveActivity(entry);
assert.equal(requests.length,0);
const saved=[];
const recorder=createDraftRecorder(e=>saved.push(e),5);
recorder.schedule('first','chatgpt','standard');
recorder.schedule('latest','chatgpt','standard');
await new Promise(r=>setTimeout(r,20));
assert.equal(saved.length,1);
assert.equal(saved[0].text,'latest');
recorder.schedule('revision','chatgpt','standard');
await new Promise(r=>setTimeout(r,20));
assert.equal(saved[0].clientId,saved[1].clientId);
assert(saved[1].revision>saved[0].revision);
recorder.schedule('pending','chatgpt','standard');
recorder.reset();
await new Promise(r=>setTimeout(r,20));
assert.equal(saved.length,2,'Cleanup cancels pending drafts');
recorder.schedule('new draft','chatgpt','standard');
await new Promise(r=>setTimeout(r,20));
assert.notEqual(saved[2].clientId,saved[0].clientId);
recorder.reset();
console.log('Activity consent, account boundaries, and draft debounce passed.');
