import assert from 'node:assert/strict';
import { validateActivity,validatePreferences,validateActivityPage,validateOptimization,DISCLOSURE_VERSION } from './activity-validation.js';
const id='ea175593-ae64-4b3a-9652-c5d608d4e0c7';
const draft={kind:'draft',clientId:id,text:'A draft',platform:'chatgpt',mode:'standard',revision:1};
assert.equal(validateActivity(draft).text,'A draft');
for(const value of [{...draft,clientId:'bad'},{...draft,text:''},{...draft,text:'x'.repeat(6001)},{...draft,text:'x\0y'},{...draft,revision:0},{...draft,platform:'unrelated-site'},{...draft,mode:'bad'}]) assert.throws(()=>validateActivity(value));
const search={kind:'search',clientId:id,text:'email',category:'all',resultCount:3};
assert.equal(validateActivity(search).resultCount,3);
assert.throws(()=>validateActivity({...search,resultCount:-1}));
assert.throws(()=>validateActivity({...search,text:'x'.repeat(501)}));
assert.throws(()=>validateActivity({...search,userId:12,kind:'other'}));
assert.deepEqual(validatePreferences({saveDrafts:false,saveSearches:false,disclosureVersion:DISCLOSURE_VERSION}),{saveDrafts:false,saveSearches:false,disclosureVersion:DISCLOSURE_VERSION});
assert.throws(()=>validatePreferences({saveDrafts:'false',saveSearches:false,disclosureVersion:DISCLOSURE_VERSION}));
assert.throws(()=>validatePreferences({saveDrafts:true,saveSearches:true,disclosureVersion:'old'}));
assert.deepEqual(validateActivityPage({}),{limit:50,offset:0});
assert.throws(()=>validateActivityPage({limit:1000}));
assert.throws(()=>validateActivityPage({offset:-1}));
const optimization={original:'Write a launch email',optimized:'Act as an email marketer',platform:'chatgpt',scoreDelta:10,scoreOriginal:null,scoreOptimized:null};
assert.equal(validateOptimization(optimization),optimization);
assert.throws(()=>validateOptimization({...optimization,scoreDelta:'not a number'}));
assert.throws(()=>validateOptimization({...optimization,clientEventId:'bad'}));
console.log('Activity input validation passed.');
